# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s

# sys.path path, space-separated, used to search for modules
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to include in 'slug'
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded
# from sys.path as keys in script_location
# version_locations =

# version table name
# version_table = alembic_version

# version table schema
# version_table_schema =

# set to 'true' to write stdout to log file
# write_stdout = false

# database connection URL - overwritten in env.py from config.py settings
sqlalchemy.url = postgresql://insightflow_admin:secureDBPassword123@localhost:5432/insightflow_ops

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
