"""Initial migration

Revision ID: 0f6736b8f35d
Revises: None
Create Date: 2026-06-27 02:24:06.817633

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # Added for sqlmodel compatibility
import pgvector


# revision identifiers, used by Alembic.
revision = '0f6736b8f35d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS insightflow_system")
    op.create_table('tenants',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subscription_tier', sqlmodel.sql.sqltypes.AutoString(length=50), server_default='Growth', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id'),
    schema='insightflow_system'
    )
    op.create_table('anomaly_alerts',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('target_metric', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('detected_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('deviation_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['insightflow_system.tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('alert_id'),
    schema='insightflow_system'
    )
    op.create_table('data_sources',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('encrypted_credentials', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['insightflow_system.tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('source_id'),
    schema='insightflow_system'
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['insightflow_system.tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    schema='insightflow_system'
    )
    op.create_index(op.f('ix_insightflow_system_users_email'), 'users', ['email'], unique=True, schema='insightflow_system')
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['insightflow_system.users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id'),
    schema='insightflow_system'
    )
    op.create_table('forecast_runs',
    sa.Column('forecast_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('target_metric', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('forecast_model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('historical_start_date', sa.DateTime(), nullable=False),
    sa.Column('forecast_end_date', sa.DateTime(), nullable=False),
    sa.Column('forecast_results', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['insightflow_system.users.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['insightflow_system.tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('forecast_id'),
    schema='insightflow_system'
    )
    op.create_table('rca_reports',
    sa.Column('rca_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['insightflow_system.anomaly_alerts.alert_id'], ),
    sa.PrimaryKeyConstraint('rca_id'),
    schema='insightflow_system'
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['insightflow_system.users.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['insightflow_system.tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    schema='insightflow_system'
    )
    op.create_table('semantic_metrics',
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sql_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['insightflow_system.data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    schema='insightflow_system'
    )
    op.create_table('semantic_tables',
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('column_definitions', sa.JSON(), nullable=False),
    sa.Column('business_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['insightflow_system.data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('table_id'),
    schema='insightflow_system'
    )
    op.create_table('agent_runs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['insightflow_system.conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('run_id'),
    schema='insightflow_system'
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('message_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_sql', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visualization_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['insightflow_system.conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    schema='insightflow_system'
    )
    op.create_table('report_widgets',
    sa.Column('widget_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('query_sql', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visualization_config', sa.JSON(), nullable=False),
    sa.Column('layout_position', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['insightflow_system.reports.report_id'], ),
    sa.PrimaryKeyConstraint('widget_id'),
    schema='insightflow_system'
    )
    op.create_table('agent_logs',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('log_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_snapshot', sa.JSON(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['insightflow_system.agent_runs.run_id'], ),
    sa.PrimaryKeyConstraint('log_id'),
    schema='insightflow_system'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_logs', schema='insightflow_system')
    op.drop_table('report_widgets', schema='insightflow_system')
    op.drop_table('chat_messages', schema='insightflow_system')
    op.drop_table('agent_runs', schema='insightflow_system')
    op.drop_table('semantic_tables', schema='insightflow_system')
    op.drop_table('semantic_metrics', schema='insightflow_system')
    op.drop_table('reports', schema='insightflow_system')
    op.drop_table('rca_reports', schema='insightflow_system')
    op.drop_table('forecast_runs', schema='insightflow_system')
    op.drop_table('conversations', schema='insightflow_system')
    op.drop_index(op.f('ix_insightflow_system_users_email'), table_name='users', schema='insightflow_system')
    op.drop_table('users', schema='insightflow_system')
    op.drop_table('data_sources', schema='insightflow_system')
    op.drop_table('anomaly_alerts', schema='insightflow_system')
    op.drop_table('tenants', schema='insightflow_system')
    op.execute("DROP SCHEMA IF EXISTS insightflow_system CASCADE")
    # ### end Alembic commands ###
